Fix that cannot resolve syncable objects in change
makeflow/syncable pull request #41
Opened 2019-07-18 07:53 UTC by hardo

2019-07-18 10:31 UTC, hardo commented on core/src/library/syncable/syncable-container.ts
> +        ? ref.map(ref => this.removeSyncable(ref))
Require

2019-07-30 14:16 UTC, vilicvane requested changes

2019-07-30 14:16 UTC, vilic commented on client/src/library/client.ts
>      let refs = _.flatMap(queryEntries, ([, query]) => {
`_.flatMapDeep`

2019-07-30 14:16 UTC, vilic commented on server/src/library/server/server.ts
>        _.flatMap(queryEntries, ([, query]) =>
同上

2019-07-31 14:23 UTC, vilicvane approved these changes

2019-07-31 14:54 UTC, merged